#!/bin/bash

GITHUB="git@github.com"

if [ "$GITHUB" == $(git remote -v | grep -o $GITHUB | head -1) ]; then
  git config --local user.email gokevinvan@gmail.com
  git config --local user.name "kevinjom"
fi

